# Site settings
title: Interactive Art / Creative Code
email: abach@saic.edu
description: > # this means to ignore newlines until "baseurl:"
  The pretty course website fro ARTTECH-3135 Interactive Art/Creative Code Spring 2019 at SAIC
baseurl: "/ARTTECH3135-spring2019" # the subpath of your site, e.g. /blog/
url: "http://ajbajb.github.io" # the base hostname & protocol for your site
github_username: ajbajb

timezone: America/Chicago

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

collections:
  assignments:
    output: true

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
